# Amazon fine food reviews - Sentiment analysis

In [3]:
#importing the dependencies
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GroupShuffleSplit,train_test_split, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer,ENGLISH_STOP_WORDS
from sklearn.pipeline import Pipeline
import re
from sklearn.metrics import confusion_matrix,f1_score,classification_report

In [4]:
df=pd.read_csv("Reviews.csv")

In [5]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [6]:
#checking for null values in the dataset
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [7]:
#dropping the features that are not necessary
df=df.drop(columns=['Id','UserId','ProfileName','HelpfulnessNumerator','HelpfulnessDenominator','Time'])

In [8]:
#checking duplicate values in the Text and Summary features
df[['Text','Summary']].duplicated().sum()

np.int64(173484)

In [9]:
#only the first occurence of the rows are kept
df=df.drop_duplicates(subset=['Text','Summary'],keep='first')

In [10]:
df.head()

,ProductId,Score,Summary,Text
0,B001E4KFG0,5,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,B00813GRG4,1,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,B000LQOCH0,4,"""Delight"" says it all",This is a confection that has been around a fe...
3,B000UA0QIQ,2,Cough Medicine,If you are looking for the secret ingredient i...
4,B006K2ZZ7K,5,Great taffy,Great taffy at a great price. There was a wid...

In [11]:
df.shape

(394970, 4)

### Mapping scores to sentiment
- 1-2 = 0
-    3      = 1
- 4-5 = 2

In [12]:
def map_sentiment(score):
    if(score<=2):
        return 0
    elif score==3:
        return 1
    else:
        return 2
df['Sentiment']=df['Score'].apply(map_sentiment)

In [13]:
y=df['Sentiment']

In [14]:
y

0         2
1         0
2         2
3         0
4         2
         ..
568449    2
568450    0
568451    2
568452    2
568453    2
Name: Sentiment, Length: 394970, dtype: int64

In [15]:
y.value_counts()

Sentiment
2    307787
0     57346
1     29837
Name: count, dtype: int64

In [16]:
x=df.drop(columns=['Score','Sentiment','ProductId'])

In [17]:
x.isnull().sum()

Summary    3
Text       0
dtype: int64

In [18]:
x['Summary']=x['Summary'].fillna('')

In [19]:
x.isnull().sum()

Summary    0
Text       0
dtype: int64

In [20]:
x['combined_text']=x['Summary']+' '+x['Text']

In [21]:
#removing the html entities
def clean_text(text):
    text = re.sub(r'&\w+;', ' ', text)      # HTML entities like &nbsp; &amp; &quot;
    text = re.sub(r'<.*?>', ' ', text)       # HTML tags like <br>, <a href=...>
    text = re.sub(r'[^a-zA-Z\s]', ' ', text) # strip digits/special symbols, keep letters
    text = re.sub(r'\s+', ' ', text).strip() # collapse extra whitespace
    return text
x['combined_text']=x['combined_text'].apply(clean_text)

In [22]:
#removing the negation words from the stop words
negation_words={'not', 'no', 'nor', 'never', 'none', 'nothing', 'nowhere', 
                   'neither', "n't", 'cannot', "don't", "doesn't", "didn't",
                   "won't", "wouldn't", "can't", "couldn't", "shouldn't",
                   "isn't", "aren't", "wasn't", "weren't", "hasn't", "haven't"}
#adding the domain words into the custom_words
domain_words={'amazon','product','item','br','href'}
custom_words=ENGLISH_STOP_WORDS-(negation_words)| domain_words

In [23]:
#GroupShuffleSplit is used to prevent reviews of same product end up in both train and test data, which may cause data leakage
groups=df['ProductId']
gss=GroupShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
train_idx,test_idx=next(gss.split(x['combined_text'],y,groups=groups))
x_train,x_test,y_train,y_test=x['combined_text'].iloc[train_idx],x['combined_text'].iloc[test_idx],y.iloc[train_idx],y.iloc[test_idx]

In [30]:
feature_extraction=TfidfVectorizer(min_df=20,stop_words=list(custom_words),lowercase=True, ngram_range=(1,2))
x_train_tfidf=feature_extraction.fit_transform(x_train)
x_test_tfidf=feature_extraction.transform(x_test)

In [29]:
[w for w in feature_extraction.get_feature_names_out() if 'nbsp' in w or 'amp' in w]

['abdominal cramping',
 'abdominal cramps',
 'able sample',
 'actually sampled',
 'ad campaign',
 'added shampoo',
 'advertising campaign',
 'alleviate cramps',
 'allow sample',
 'allowed sample',
 'allows ample',
 'amp',
 'amped',
 'ample',
 'ample portion',
 'ample room',
 'ample serving',
 'ample supply',
 'ample taste',
 'ample time',
 'ample water',
 'amplified',
 'amplifies',
 'amplify',
 'amply',
 'amps',
 'amputation',
 'anxious sample',
 'applied shampoo',
 'asking samplers',
 'aspect shampoo',
 'attention shampoo',
 'available sample',
 'average shampoo',
 'away samples',
 'away shampoo',
 'away vampires',
 'awesome sampler',
 'awesome shampoo',
 'baby shampoo',
 'backpack camping',
 'backpacking camping',
 'bad campbell',
 'bad cramps',
 'bad shampoo',
 'bag sample',
 'bag sampled',
 'bag sampler',
 'bag shampoo',
 'bar example',
 'bar sample',
 'bars sample',
 'basecamp',
 'based sample',
 'based shampoo',
 'basic shampoo',
 'beach campsite',
 'bean sampler',
 'beauty shampoo',
 'best champagne',
 'best example',
 'best sampled',
 'best shampoo',
 'better campbell',
 'better campbells',
 'better example',
 'better sample',
 'better shampoo',
 'better shampoos',
 'bit damp',
 'bit example',
 'bit shampoo',
 'bloating cramping',
 'blood sample',
 'body shampoo',
 'bold sampler',
 'bonus sample',
 'books pamphlets',
 'boost shampoo',
 'boot camp',
 'bottle shampoo',
 'bottles shampoo',
 'bought camping',
 'bought sample',
 'bought sampler',
 'bought samples',
 'bought shampoo',
 'box damp',
 'box sample',
 'box sampled',
 'box sampler',
 'box samples',
 'box stamped',
 'brand sample',
 'brand sampler',
 'brand sampling',
 'brand shampoo',
 'brand shampoos',
 'brands sampled',
 'brands sampler',
 'breakage shampoo',
 'breakfast champions',
 'bring camping',
 'bringing camping',
 'brought sample',
 'bull amp',
 'butter example',
 'butter sampled',
 'buy campbell',
 'buy camping',
 'buy sample',
 'buy sampler',
 'buy samples',
 'buy shampoo',
 'buying campbell',
 'buying sample',
 'buying sampler',
 'buying samples',
 'buying shampoo',
 'came sample',
 'came sampler',
 'came samples',
 'camp',
 'camp cooking',
 'camp love',
 'camp not',
 'camp site',
 'camp stove',
 'camp summer',
 'camp went',
 'campaign',
 'campaign california',
 'campaigns',
 'campaigns involving',
 'campania',
 'campanini',
 'campari',
 'campari unicum',
 'campbell',
 'campbell best',
 'campbell better',
 'campbell brand',
 'campbell chicken',
 'campbell chucky',
 'campbell chunky',
 'campbell condensed',
 'campbell cream',
 'campbell discontinue',
 'campbell firehouse',
 'campbell green',
 'campbell healthy',
 'campbell low',
 'campbell makes',
 'campbell mushroom',
 'campbell new',
 'campbell not',
 'campbell pepper',
 'campbell pork',
 'campbell progresso',
 'campbell select',
 'campbell slow',
 'campbell soup',
 'campbell soups',
 'campbell tomato',
 'campbell version',
 'campbells',
 'campbells chicken',
 'campbells chunky',
 'campbells clam',
 'campbells cream',
 'campbells soup',
 'campbells soups',
 'campbells tomato',
 'camped',
 'campell',
 'camper',
 'camper best',
 'camper bought',
 'camper camp',
 'camper got',
 'camper great',
 'camper little',
 'camper not',
 'camper ordered',
 'camper stands',
 'camper tastes',
 'camper thank',
 'campers',
 'campfire',
 'campfire cooking',
 'campfire just',
 'campfire pork',
 'campfire seafood',
 'campfires',
 'campground',
 'camphor',
 'camping',
 'camping add',
 'camping backpacking',
 'camping car',
 'camping don',
 'camping emergency',
 'camping fishing',
 'camping food',
 'camping gear',
 'camping good',
 'camping great',
 'camping hiking',
 'camping just',
 'camping keeping',
 'camping kids',
 'camping like',
 'camping little',
 'camping long',
 'camping love',
 'camping meal',
 'camping no',
 'camping not',
 'camping picnics',
 'camping quick',
 'camping road',
 'camping summer',
 'camping taking',
 'camping thing',
 'camping time',
 'camping travel',
 'camping traveling',
 'camping travelling',
 'camping trip',
 'camping trips',
 'camping use',
 'camping using',
 'camping ve',
 'camping weight',
 'campofrio',
 'campout',
 'camps',
 'campsite',
 'campsite memorable',
 'campus',
 'campy',
 'campy death',
 'cans campbell',
 'car camping',
 'care shampoo',
 'carry camping',
 'case example',
 'cats sampled',
 'champ',
 'champagne',
 'champagne cocktail',
 'champagne cocktails',
 'champagne really',
 'champagne taste',
 'champagne teas',
 'champagne toast',
 'champagne vinegar',
 'champagne wine',
 'champagne yeast',
 'champaign',
 'champaigne',
 'champignon',
 'champignon gold',
 'champion',
 'champion foods',
 'champions',
 'championship',
 'championship bbq',
 'champlain',
 'champs',
 'chance sample',
 'change shampoo',
 'cheap champagne',
 'cheap shampoo',
 'cheaper shampoos',
 'cheapest shampoo',
 'cheese sampler',
 'chemicals shampoo',
 'chili campbell',
 'chocolate example',
 'chocolate sample',
 'chocolate sampler',
 'choice campbell',
 'chose sampler',
 'city sampled',
 'clamp',
 'clamped',
 'clamping',
 'clarifying shampoo',
 'clean shampoo',
 'cleansing shampoo',
 'clear example',
 'clear shampoo',
 'clear shampoos',
 'clearly stamped',
 'coffee camping',
 'coffee example',
 'coffee sample',
 'coffee sampled',
 'coffee sampler',
 'coffee samplers',
 'coffee samples',
 'coffee sampling',
 'coffees sampler',
 'cold damp',
 'cold sampler',
 'college campus',
 'color shampoo',
 'combination shampoo',
 'combined shampoo',
 'comes shampoos',
 'companion shampoo',
 'company sample',
 'comparison campbell',
 'complimentary sample',
 'complimentary sampler',
 'complimentary samples',
 'conditioner shampoo',
 'conditioning shampoo',
 'conditioning shampoos',
 'consider sample',
 'consistency shampoo',
 'contained shampoo',
 'container shampoo',
 'contents example',
 'cookie sample',
 'cookies sample',
 'cooking camping',
 'cooking example',
 'corresponding shampoo',
 'costco samples',
 'count sampler',
 'couple sample',
 'couple samples',
 'course sample',
 'cover damp',
 'crackers sample',
 'cramp',
 'cramp time',
 'cramped',
 'cramping',
 'cramping bloating',
 'cramping day',
 'cramping diarrhea',
 'cramping gas',
 'cramping massive',
 'cramping not',
 'cramping running',
 'cramping soreness',
 'cramping symptoms',
 'cramping tea',
 'cramps',
 'cramps away',
 'cramps cause',
 'cramps day',
 'cramps days',
 'cramps diarrhea',
 'cramps especially',
 'cramps fact',
 'cramps gas',
 'cramps gone',
 'cramps headaches',
 'cramps helps',
 'cramps just',
 'cramps legs',
 'cramps life',
 'cramps like',
 'cramps long',
 'cramps mild',
 'cramps month',
 'cramps mood',
 'cramps need',
 'cramps night',
 'cramps no',
 'cramps pain',
 'cramps stopped',
 'cramps today',
 'cramps use',
 'cramps used',
 'cramps ve',
 'crampy',
 'creamy shampoo',
 'crowd stampeded',
 'cup sample',
 'cup sampler',
 'cup samplers',
 'cup samples',
 'cups sample',
 'cups sampled',
 'cups sampler',
 'cups samplers',
 'current shampoo',
 'customer sample',
 'daily shampoo',
 'damp',
 'damp cloth',
 'damp cold',
 'damp dry',
 'damp hair',
 'damp no',
 'damp not',
 'damp paper',
 'damp sawdust',
 'damp soft',
 'damp soil',
 'damp towel',
 'damp wet',
 'dampen',
 'dampened',
 'dampens',
 'damper',
 'dampness',
 'dandruff shampoo',
 'dandruff shampoos',
 'date example',
 'date stamp',
 'date stamped',
 'day example',
 'day sample',
 'day shampoo',
 'days shampoo',
 'days shampoos',
 'decaf sampler',
 'decent shampoo',
 'decided sample',
 'delicious campbell',
 'delicious camping',
 'delicious sampled',
 'delighted tampa',
 'desk lamp',
 'did campbell',
 'did sample',
 'did shampoo',
 'diet example',
 'difference shampoo',
 'difference shampoos',
 'different sample',
 'different sampler',
 'different samples',
 'different shampoo',
 'different shampoos',
 'dinner campfire',
 'disappointed sampler',
 'disappointed shampoo',
 'dish example',
 'dishes example',
 'dispense shampoo',
 'does shampoo',
 'dog shampoo',
 'don cramp',
 'dose tamp',
 'dove shampoo',
 'downside shampoo',
 'drank sample',
 'dressing example',
 'drink example',
 'dry shampoo',
 'dry shampoos',
 'drying shampoo',
 'eager sample',
 'easily shampoo',
 'easy camping',
 'eat campbell',
 'eating campbell',
 'effect example',
 'effective shampoo',
 'encampment',
 'end shampoo',
 'enjoyed sample',
 'enjoyed sampler',
 'enjoyed sampling',
 'enjoyed shampoo',
 'entire sampler',
 'envelope shampoo',
 'especially camping',
 'essence champignon',
 'everyday shampoo',
 'example',
 'example add',
 'example adding',
 'example better',
 'example bittersweet',
 'example chicken',
 'example chocolate',
 'example coffee',
 'example cream',
 'example cup',
 'example cups',
 'example definitely',
 'example different',
 'example doesn',
 'example don',
 'example enjoy',
 'example expensive',
 'example fine',
 'example fruit',
 'example getting',
 'example good',
 'example got',
 'example great',
 'example half',
 'example healthy',
 'example honey',
 'example just',
 'example keurig',
 'example like',
 'example little',
 'example ll',
 'example local',
 'example lot',
 'example love',
 'example make',
 'example mix',
 'example need',
 'example no',
 'example not',
 'example olive',
 'example ordered',
 'example picture',
 'example potato',
 'example really',
 'example red',
 'example said',
 'example say',
 'example taste',
 'example tea',
 'example thing',
 'example time',
 'example took',
 'example tried',
 'example try',
 'example use',
 'example used',
 'example using',
 'example usually',
 'example ve',
 'example want',
 'examples',
 'examples not',
 'excellent example',
 'excellent sampler',
 'excellent shampoo',
 'excited sampler',
 'expect sampler',
 'expensive sampler',
 'expensive shampoo',
 'expensive shampoos',
 'expert sampling',
 'fact shampoo',
 'family camping',
 'family sampled',
 'fan campbell',
 'fantastic shampoo',
 'far sample',
 'far shampoo',
 'favorite campbell',
 'favorite shampoo',
 'feel shampoo',
 'feeling shampoo',
 'feldkamp',
 'fine example',
 'fine sample',
 'fine shampoo',
 'finish sample',
 'finished sample',
 'flavor ample',
 'flavor example',
 'flavor sample',
 'flavor sampled',
 'flavor sampler',
 'flavored sample',
 'flavored sampler',
 'flavors example',
 'flavors sample',
 'flavors sampled',
 'flavors sampler',
 'flowers champagne',
 'follow example',
 'food example',
 'food sampled',
 'food samples',
 'food sampling',
 'foods example',
 'forte sampler',
 'forward sampling',
 'fragrance shampoo',
 'free sample',
 'free sampler',
 'free samples',
 'free shampoo',
 'fruit sampler',
 'fun sample',
 'fun sampling',
 'funny campy',
 'gas cramping',
 'gas cramps',
 'gave sample',
 'gave sampler',
 'gave samples',
 'gave shampoo',
 'gentle shampoo',
 'getting sample',
 'getting sampler',
 'gift sample',
 'gift sampler',
 'gift samples',
 'given sample',
 'given samples',
 'gives samples',
 'giving samples',
 'glass champagne',
 'going camping',
 'going sample',
 'good campbell',
 'good camping',
 'good example',
 'good examples',
 'good sample',
 'good sampled',
 'good sampler',
 'good sampling',
 'good shampoo',
 'good shampoos',
 'got sample',
 'got sampler',
 'got samples',
 'got shampoo',
 'gotten sample',
 'gotten sampler',
 'grampa',
 'gramps',
 'grand champion',
 'great campfire',
 'great camping',
 'great champagne',
 'great example',
 'great sample',
 'great sampler',
 'great sampling',
 'great shampoo',
 'grind tamp',
 'grinding tamping',
 'ground tamped',
 'guise campbell',
 'hair shampoo',
 'hair shampooing',
 'hair shampoos',
 'half shampoo',
 'hamper',
 'hampered',
 'hampering',
 'hampshire',
 'hampton',
 'hampton inn',
 'handing samples',
 'happy camper',
 'happy campers',
 'happy sample',
 'happy sampler',
 'haven sampled',
 'having sample',
 'having sampled',
 'having shampoo',
 'heat lamp',
 'helps cramps',
 'hiking camping',
 'home camping',
 'home sample',
 'home samples',
 'hours shampoo',
 'house camping',
 'husband sampled',
 'idea sampler',
 'idea shampoo',
 'important shampoo',
 'impressed shampoo',
 'included sample',
 'included sampler',
 'included samples',
 'including campbell',
 'inexpensive shampoo',
 'influenster sample',
 'ingredient shampoo',
 'ingredients example',
 'ingredients shampoo',
 'initially sampled',
 'instead shampoo',
 'interested sampling',
 'investment sample',
 'iron example',
 'jaegermeister campari',
 'job shampoo',
 'juice example',
 'just example',
 'just sample',
 'just sampled',
 'just shampoo',
 'kickstarter campaign',
 'kind sampler',
 'know campbell',
 'lake champlain',
 'lamp',
 'lamps',
 'large sampler',
 'larger sample',
 'lather shampoo',
 'lathering shampoo',
 'leading camp',
 'leak shampoo',
 'leg cramps',
 'lengths shampoo',
 'let sample',
 'like campari',
 'like campbell',
 'like campbells',
 'like campfire',
 'like camping',
 'like champ',
 'like champagne',
 'like champion',
 'like damp',
 'like example',
 'like pamper',
 'like sample',
 'like sampler',
 'like samples',
 'like shampoo',
 'like shampoos',
 'like swamp',
 'liked sample',
 'liked sampler',
 'liked shampoo',
 'line shampoo',
 'line shampoos',
 'little champions',
 'little damp',
 'little sample',
 'little sampler',
 'little shampoo',
 'look sample',
 'looking sample',
 'looking sampler',
 'looking shampoo',
 'lot shampoo',
 'lot shampoos',
 'lotion shampoo',
 'love camp',
 'love campbell',
 'love camping',
 'love champagne',
 'love pampered',
 'love sample',
 'love sampler',
 'love shampoo',
 'loved sampler',
 'loved shampoo',
 'lovely shampoo',
 'lover sampler',
 'lovers sampler',
 'loves shampoo',
 'make cramps',
 'make shampoo',
 'marketing campaign',
 'matching shampoo',
 'maybe sample',
 'meal camping',
 'meal example',
 'members sampled',
 'men shampoo',
 'menstrual cramps',
 'mess shampoo',
 'mild shampoo',
 'mini sampler',
 'mint shampoo',
 'minutes shampoo',
 'mix example',
 'mixed sample',
 'moisture shampoo',
 'moisturizing shampoo',
 'moisturizing shampoos',
 'monster amp',
 'morning camping',
 'morning shampoo',
 'muscle cramping',
 'muscle cramps',
 'native tampa',
 'nearby campfire',
 'need shampoo',
 'negative shampoo',
 'never sampled',
 'never shampoo',
 'new hampshire',
 'new shampoo',
 'nice sample',
 'nice sampler',
 'nice sampling',
 'nice shampoo',
 'night cramps',
 'night shampoo',
 'no cramping',
 'no cramps',
 'no shampoo',
 'no tamper',
 'normal shampoo',
 'not cramp',
 'not example',
 'not sample',
 'not sampled',
 'not sampler',
 'not samples',
 'not sampling',
 'not shampoo',
 'not shampoos',
 'not tamp',
 'not tampered',
 'noticed shampoo',
 'nourish shampoo',
 'nourishing shampoo',
 'oatmeal shampoo',
 'odor shampoo',
 'offer sample',
 'offered sample',
 'offered sampler',
 'offered samples',
 'offering samples',
 'oil example',
 'oil samples',
 'oil shampoo',
 'ok shampoo',
 'old shampoo',
 'older shampoo',
 'open sample',
 'open shampoo',
 'opened sample',
 'opened shampoo',
 'opportunity sample',
 'options example',
 'options sample',
 'order sample',
 'order sampler',
 'order samplers',
 'ordered sample',
 'ordered sampler',
 'ordered samplers',
 'ordered shampoo',
 'ordering sample',
 'ordering sampler',
 'organic example',
 'organic sampler',
 'ounce campbell',
 'ounce example',
 'ounce sample',
 'ounce shampoo',
 'overall shampoo',
 'oz sample',
 'pack camping',
 'pack example',
 'pack sample',
 'pack sampler',
 'package sample',
 'packaged damp',
 'packages camping',
 'packaging shampoo',
 'packet sample',
 'pain cramps',
 'painful cramping',
 'painful cramps',
 'pamper',
 'pampered',
 'pampered chef',
 'pampering',
 'pamphlet',
 'pamphlets',
 'pamphlets available',
 'pamprin',
 'parampara',
 'particular sampler',
 'passed samples',
 'pasta example',
 'people sample',
 'people samples',
 'perfect camping',
 'perfect example',
 'perfect sampler',
 'pet shampoo',
 'picked sample',
 'place shampoo',
 'pleased shampoo',
 'pleasure sampling',
 'plenty campbell',
 'plus shampoo',
 'pms cramps',
 'pod sample',
 'point shampoo',
 'pop camper',
 'postage stamp',
 'pound sampler',
 'pre amp',
 'pre shampoo',
 'preamp',
 'prescription shampoo',
 'prevent cramps',
 'previous shampoo',
 'price campbell',
 'price sample',
 'price shampoo',
 'price shampoos',
 'priced shampoo',
 'prime example',
 'probably sample',
 'problem shampoo',
 'problem shampoos',
 'problems shampoo',
 'products example',
 'products shampoo',
 'propaganda campaign',
 'properly shampoo',
 'provides ample',
 'purchase sample',
 'purchase sampler',
 'purchased sample',
 'purchased sampler',
 'purchased shampoo',
 'quality shampoo',
 'ramp',
 'ramp flavor',
 'rampage',
 'rampant',
 'ramped',
 'ramping',
 'ramps',
 'range shampoos',
 'rate shampoo',
 'receive sampler',
 'received sample',
 'received sampler',
 'received samples',
 'received shampoo',
 'receiving sample',
 'recieved sample',
 'recommend sample',
 'recommend sampler',
 'recommend sampling',
 'recommend shampoo',
 'regular campbell',
 'regular shampoo',
 'regular shampoos',
 'repair shampoo',
 'request sample',
 'rest sample',
 'results shampoo',
 'results shampoos',
 'revamp',
 'revamped',
 'revamping',
 'review campbell',
 'review sample',
 'review shampoo',
 'reviewed shampoo',
 'reviewing shampoo',
 'reviews shampoo',
 'right camping',
 'right shampoo',
 'right shampooing',
 'rinse shampoo',
 'roast sampler',
 'routine shampoo',
 'runs rampant',
 'safe shampoo',
 'said shampoo',
 'salad example',
 'salon shampoos',
 'salt lamp',
 'salt sampler',
 'sample',
 'sample arrived',
 'sample bag',
 'sample bags',
 'sample banana',
 'sample bar',
 'sample bars',
 'sample beef',
 'sample bite',
 'sample bottle',
 'sample bottles',
 'sample bought',
 'sample box',
 'sample brand',
 'sample buy',
 'sample buying',
 'sample bzzagent',
 'sample came',
 'sample candy',
 'sample cans',
 'sample caramel',
 'sample case',
 'sample cat',
 'sample cats',
 'sample cereal',
 'sample chips',
 ...]

## Creating the base learner baselines

In [ ]:
lr=LogisticRegression(max_iter=1000,class_weight='balanced')
lr.fit(x_train_tfidf,y_train)
y_pred=lr.predict(x_test_tfidf)
print(classification_report(y_test,y_pred))

In [ ]:
dt=DecisionTreeClassifier(class_weight='balanced',max_depth=50,random_state=42)
dt.fit(x_train_tfidf,y_train)
y_pred_dt=dt.predict(x_test_tfidf)
print(classification_report(y_test,y_pred_dt))

"dt=DecisionTreeClassifier(class_weight='balanced',max_depth=50,random_state=42)\ndt.fit(x_train_tfidf,y_train)\ny_pred_dt=dt.predict(x_test_tfidf)\nprint(classification_report(y_test,y_pred_dt))"

In [ ]:
rf=RandomForestClassifier(class_weight='balanced',n_estimators=50,max_depth=50,random_state=42,n_jobs=-1)
rf.fit(x_train_tfidf,y_train)
y_pred_rf=rf.predict(x_test_tfidf)
print(classification_report(y_test,y_pred_rf))

"rf=RandomForestClassifier(class_weight='balanced',n_estimators=50,max_depth=50,random_state=42,n_jobs=-1)\nrf.fit(x_train_tfidf,y_train)\ny_pred_rf=rf.predict(x_test_tfidf)\nprint(classification_report(y_test,y_pred_rf))"

In [ ]:
'''mnb=MultinomialNB()
mnb.fit(x_train_tfidf,y_train)
y_pred_mnb=mnb.predict(x_test_tfidf)
print(classification_report(y_test,y_pred_mnb))'''

'mnb=MultinomialNB()\nmnb.fit(x_train_tfidf,y_train)\ny_pred_mnb=mnb.predict(x_test_tfidf)\nprint(classification_report(y_test,y_pred_mnb))'